### ISSUE TITLE
A rendering error caused the client to crash

### ISSUE THREAD

**Issue by Polaris-Canis-latrans** [petrolpark/Create-Library#79]
**Describe the bug**

I play your pquality mod on my 1.20.1 server，when I move the mouse over an item with quality，my client crashed.

**To Reproduce**

1. Join my server.
2. Move mouse to an item that have quality(traveler's backpack or vanilla slots)
3. My client crashed.
4. I tried playing your mod on singleplayer, and the game didn't crash, but the items I obtained didn't have any quality.

**Expected Behavior**

My Client don't crash. 

**error log**
Description: Rendering screen

java.lang.NullPointerException: Cannot invoke "net.minecraft.server.MinecraftServer.m_206579_()" because the return value of "net.minecraftforge.server.ServerLifecycleHooks.getCurrentServer()" is null
	at com.petrolpark.contamination.Contaminant.getLocation(Contaminant.java:115) ~[petrolpark-1.20.1-1.4.20-all.jar%23528!/:1.4.20] {re:classloading}
	at com.petrolpark.contamination.Contaminant.compareTo(Contaminant.java:120) ~[petrolpark-1.20.1-1.4.20-all.jar%23528!/:1.4.20] {re:classloading}
	at java.util.TreeMap.compare(TreeMap.java:1606) ~[?:?] {}
	at java.util.TreeMap.addEntryToEmptyMap(TreeMap.java:810) ~[?:?] {}
	at java.util.TreeMap.put(TreeMap.java:819) ~[?:?] {}
	at java.util.TreeMap.put(TreeMap.java:568) ~[?:?] {}
	at java.util.TreeSet.add(TreeSet.java:261) ~[?:?] {}
	at java.util.AbstractCollection.addAll(AbstractCollection.java:338) ~[?:?] {re:mixin}
	at java.util.TreeSet.addAll(TreeSet.java:315) ~[?:?] {}
	at com.petrolpark.contamination.ItemContamination.<init>(ItemContamination.java:38) ~[petrolpark-1.20.1-1.4.20-all.jar%23528!/:1.4.20] {re:mixin,re:classloading}
	at com.petrolpark.contamination.ItemContamination.create(ItemContamination.java:17) ~[petrolpark-1.20.1-1.4.20-all.jar%23528!/:1.4.20] {re:mixin,re:classloading}
	at net.minecraft.world.item.ItemStack.getContamination(ItemStack.java:5100) ~[client-1.20.1-20230612.114412-srg.jar%23584!/:?] {re:mixin,xf:fml:calio:calio_remove_flag,xf:fml:forge:itemstack,re:classloading,xf:fml:calio:calio_remove_flag,xf:fml:forge:itemstack,pl:mixin:APP:apoli.mixins.json:ItemStackMixin,pl:mixin:APP:useitemonblockevent.mixins.json:ItemStackMixin,pl:mixin:APP:tombstone.mixins.json:ItemStackMixin,pl:mixin:APP:veinmining.mixins.json:ItemStackMixin,pl:mixin:APP:glitchcore.mixins.json:MixinItemStack,pl:mixin:APP:etched.mixins.json:client.ItemStackMixin,pl:mixin:APP:canary.mixins.json:util.item_stack_tracking.ItemStackMixin,pl:mixin:APP:placebo.mixins.json:ItemStackMixin,pl:mixin:APP:petrolpark.mixins.json:ItemStackMixin,pl:mixin:APP:icterine.mixins.json:ItemStackMixin,pl:mixin:APP:pquality.mixins.json:ItemStackMixin,pl:mixin:APP:fabrication.mixins.json:f_balance.disable_prior_work_penalty.MixinItemStack,pl:mixin:APP:fabrication.mixins.json:e_mechanics.swap_conflicting_enchants.MixinItemStack,pl:mixin:APP:fabrication.mixins.json:b_utility.canhit.MixinItemStackClient,pl:mixin:APP:fabrication.mixins.json:a_fixes.adventure_tags_in_survival.MixinItemStack,pl:mixin:A}
	at com.petrolpark.contamination.ItemContamination.get(ItemContamination.java:21) ~[petrolpark-1.20.1-1.4.20-all.jar%23528!/:1.4.20] {re:mixin,re:classloading}
	at com.petrolpark.pquality.core.QualityUtil.fetchQuality(QualityUtil.java:18) ~[pquality-1.20.1-0.2.1.jar%23531!/:0.2.1] {re:mixin,re:classloading}
	at net.minecraft.world.item.ItemStack.getQuality(ItemStack.java:6076) ~[client-1.20.1-20230612.114412-srg.jar%23584!/:?] {re:mixin,xf:fml:calio:calio_remove_flag,xf:fml:forge:itemstack,re:classloading,xf:fml:calio:calio_remove_flag,xf:fml:forge:itemstack,pl:mixin:APP:apoli.mixins.json:ItemStackMixin,pl:mixin:APP:useitemonblockevent.mixins.json:ItemStackMixin,pl:mixin:APP:tombstone.mixins.json:ItemStackMixin,pl:mixin:APP:veinmining.mixins.json:ItemStackMixin,pl:mixin:APP:glitchcore.mixins.json:MixinItemStack,pl:mixin:APP:etched.mixins.json:client.ItemStackMixin,pl:mixin:APP:canary.mixins.json:util.item_stack_tracking.ItemStackMixin,pl:mixin:APP:placebo.mixins.json:ItemStackMixin,pl:mixin:APP:petrolpark.mixins.json:ItemStackMixin,pl:mixin:APP:icterine.mixins.json:ItemStackMixin,pl:mixin:APP:pquality.mixins.json:ItemStackMixin,pl:mixin:APP:fabrication.mixins.json:f_balance.disable_prior_work_penalty.MixinItemStack,pl:mixin:APP:fabrication.mixins.json:e_mechanics.swap_conflicting_enchants.MixinItemStack,pl:mixin:APP:fabrication.mixins.json:b_utility.canhit.MixinItemStackClient,pl:mixin:APP:fabrication.mixins.json:a_fixes.adventure_tags_in_survival.MixinItemStack,pl:mixin:A}
	at com.petrolpark.pquality.core.QualityUtil.getQuality(QualityUtil.java:14) ~[pquality-1.20.1-0.2.1.jar%23531!/:0.2.1] {re:mixin,re:classloading}
	at com.petrolpark.pquality.event.CommonEvents.onItemAttributeModification(CommonEvents.java:48) ~[pquality-1.20.1-0.2.1.jar%23531!/:0.2.1] {re:classloading}
	at com.petrolpark.pquality.event.__CommonEvents_onItemAttributeModification_ItemAttributeModifierEvent.invoke(.dynamic) ~[pquality-1.20.1-0.2.1.jar%23531!/:0.2.1] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.common.ForgeHooks.getAttributeModifiers(ForgeHooks.java:997) ~[forge-1.20.1-47.4.10-universal.jar%23589!/:?] {re:mixin,re:classloading,pl:mixin:APP:modernfix-forge.mixins.json:perf.faster_ingredients.ForgeHooksMixin,pl:mixin:APP:apoli.mixins.json:forge.ForgeHooksMixin,pl:mixin:APP:tombstone.mixins.json:ForgeHooksMixin,pl:mixin:A}
	at net.minecraft.world.item.ItemStack.m_41638_(ItemStack.java:890) ~[client-1.20.1-20230612.114412-srg.jar%23584!/:?] {re:mixin,xf:fml:calio:calio_remove_flag,xf:fml:forge:itemstack,re:classloading,xf:fml:calio:calio_remove_flag,xf:fml:forge:itemstack,pl:mixin:APP:apoli.mixins.json:ItemStackMixin,pl:mixin:APP:useitemonblockevent.mixins.json:ItemStackMixin,pl:mixin:APP:tombstone.mixins.json:ItemStackMixin,pl:mixin:APP:veinmining.mixins.json:ItemStackMixin,pl:mixin:APP:glitchcore.mixins.json:MixinItemStack,pl:mixin:APP:etched.mixins.json:client.ItemStackMixin,pl:mixin:APP:canary.mixins.json:util.item_stack_tracking.ItemStackMixin,pl:mixin:APP:placebo.mixins.json:ItemStackMixin,pl:mixin:APP:petrolpark.mixins.json:ItemStackMixin,pl:mixin:APP:icterine.mixins.json:ItemStackMixin,pl:mixin:APP:pquality.mixins.json:ItemStackMixin,pl:mixin:APP:fabrication.mixins.json:f_balance.disable_prior_work_penalty.MixinItemStack,pl:mixin:APP:fabrication.mixins.json:e_mechanics.swap_conflicting_enchants.MixinItemStack,pl:mixin:APP:fabrication.mixins.json:b_utility.canhit.MixinItemStackClient,pl:mixin:APP:fabrication.mixins.json:a_fixes.adventure_tags_in_survival.MixinItemStack,pl:mixin:A}
	at net.minecraft.world.item.ItemStack.m_41651_(ItemStack.java:674) ~[client-1.20.1-20230612.114412-srg.jar%23584!/:?] {re:mixin,xf:fml:calio:calio_remove_flag,xf:fml:forge:itemstack,re:classloading,xf:fml:calio:calio_remove_flag,xf:fml:forge:itemstack,pl:mixin:APP:apoli.mixins.json:ItemStackMixin,pl:mixin:APP:useitemonblockevent.mixins.json:ItemStackMixin,pl:mixin:APP:tombstone.mixins.json:ItemStackMixin,pl:mixin:APP:veinmining.mixins.json:ItemStackMixin,pl:mixin:APP:glitchcore.mixins.json:MixinItemStack,pl:mixin:APP:etched.mixins.json:client.ItemStackMixin,pl:mixin:APP:canary.mixins.json:util.item_stack_tracking.ItemStackMixin,pl:mixin:APP:placebo.mixins.json:ItemStackMixin,pl:mixin:APP:petrolpark.mixins.json:ItemStackMixin,pl:mixin:APP:icterine.mixins.json:ItemStackMixin,pl:mixin:APP:pquality.mixins.json:ItemStackMixin,pl:mixin:APP:fabrication.mixins.json:f_balance.disable_prior_work_penalty.MixinItemStack,pl:mixin:APP:fabrication.mixins.json:e_mechanics.swap_conflicting_enchants.MixinItemStack,pl:mixin:APP:fabrication.mixins.json:b_utility.canhit.MixinItemStackClient,pl:mixin:APP:fabrication.mixins.json:a_fixes.adventure_tags_in_survival.MixinItemStack,pl:mixin:A}
	at net.minecraft.client.gui.screens.Screen.m_280152_(Screen.java:246) ~[client-1.20.1-20230612.114412-srg.jar%23584!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:ScreenAccessor,pl:mixin:APP:kiwi.mixins.json:client.ScreenMixin,pl:mixin:APP:patchouli_xplat.mixins.json:client.AccessorScreen,pl:mixin:APP:refurbished_furniture.common.mixins.json:client.ScreenAccessor,pl:mixin:APP:trender.mixins.json:client.ScreenAccessor,pl:mixin:APP:configured.common.mixins.json:client.ScreenMixin,pl:mixin:APP:watut.mixins.json:client.ScreenRenderBackground,pl:mixin:APP:watut.mixins.json:client.ScreenRenderWithTooltip,pl:mixin:APP:reterraforged-common.mixins.json:ScreenInvoker,pl:mixin:APP:fabrication.mixins.json:i_woina.old_background_shade.MixinScreen,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_280553_(AbstractContainerScreen.java:169) ~[client-1.20.1-20230612.114412-srg.jar%23584!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:calio:calio_ContainerScreenAccessor,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,xf:fml:calio:calio_ContainerScreenAccessor,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:calio:calio_ContainerScreenAccessor,pl:mixin:APP:balm.mixins.json:AbstractContainerScreenAccessor,pl:mixin:APP:acceleratedrendering.feature.items.mixins.json:gui.AbstractContainerScreenMixin,pl:mixin:APP:mousetweaks.mixins.json:AbstractContainerScreenAccessor,pl:mixin:APP:crafttakestime.mixins.json:MixinContainerScreen,pl:mixin:APP:sounds.mixins.json:ui.ItemDragSoundEffect,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_280072_(AbstractContainerScreen.java:163) ~[client-1.20.1-20230612.114412-srg.jar%23584!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:calio:calio_ContainerScreenAccessor,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,xf:fml:calio:calio_ContainerScreenAccessor,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:calio:calio_ContainerScreenAccessor,pl:mixin:APP:balm.mixins.json:AbstractContainerScreenAccessor,pl:mixin:APP:acceleratedrendering.feature.items.mixins.json:gui.AbstractContainerScreenMixin,pl:mixin:APP:mousetweaks.mixins.json:AbstractContainerScreenAccessor,pl:mixin:APP:crafttakestime.mixins.json:MixinContainerScreen,pl:mixin:APP:sounds.mixins.json:ui.ItemDragSoundEffect,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.ContainerScreen.m_88315_(ContainerScreen.java:29) ~[client-1.20.1-20230612.114412-srg.jar%23584!/:?] {re:classloading}
	at net.minecraft.client.gui.screens.Screen.m_280264_(Screen.java:109) ~[client-1.20.1-20230612.114412-srg.jar%23584!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:ScreenAccessor,pl:mixin:APP:kiwi.mixins.json:client.ScreenMixin,pl:mixin:APP:patchouli_xplat.mixins.json:client.AccessorScreen,pl:mixin:APP:refurbished_furniture.common.mixins.json:client.ScreenAccessor,pl:mixin:APP:trender.mixins.json:client.ScreenAccessor,pl:mixin:APP:configured.common.mixins.json:client.ScreenMixin,pl:mixin:APP:watut.mixins.json:client.ScreenRenderBackground,pl:mixin:APP:watut.mixins.json:client.ScreenRenderWithTooltip,pl:mixin:APP:reterraforged-common.mixins.json:ScreenInvoker,pl:mixin:APP:fabrication.mixins.json:i_woina.old_background_shade.MixinScreen,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:428) ~[forge-1.20.1-47.4.10-universal.jar%23589!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:421) ~[forge-1.20.1-47.4.10-universal.jar%23589!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:965) ~[client-1.20.1-20230612.114412-srg.jar%23584!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:moonlight-common.mixins.json:GameRendererMixin,pl:mixin:APP:apoli.mixins.json:GameRendererMixin,pl:mixin:APP:mixins.oculus.json:GameRendererAccessor,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer,pl:mixin:APP:mixins.oculus.json:MixinModelViewBobbing,pl:mixin:APP:tombstone.mixins.json:GameRendererMixin,pl:mixin:APP:acceleratedrendering.core.mixins.json:GameRendererMixin,pl:mixin:APP:acceleratedrendering.feature.items.mixins.json:gui.GameRendererMixin,pl:mixin:APP:ponder-common.mixins.json:client.accessor.GameRendererAccessor,pl:mixin:APP:sodium-extra.mixins.json:prevent_shaders.MixinGameRenderer,pl:mixin:APP:immersive_aircraft.mixins.json:client.GameRendererMixin,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinGameRenderer,pl:mixin:APP:eclipticseasons.mixins.json:client.render.MixinGameRenderer,pl:mixin:APP:forge-asyncparticles-common.mixins.json:tick.MixinGameRenderer,pl:mixin:APP:tacz.mixins.json:client.GameRendererMixin,pl:mixin:APP:chloride.mixin.json:darkness.GameRendererMixin,pl:mixin:APP:realcamera-common.mixins.json:MixinGameRenderer,pl:mixin:APP:realcamera-common.mixins.json:accessor.GameRendererAccessor,pl:mixin:APP:create.mixins.json:client.GameRendererMixin,pl:mixin:APP:embeddium.mixins.json:features.gui.hooks.console.GameRendererMixin,pl:mixin:APP:fabrication.mixins.json:a_fixes.no_night_vision_flash.MixinGameRenderer,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer_NightVisionCompat,pl:mixin:APP:forge-badoptimizations.mixins.json:accessors.GameRendererAccessor,pl:mixin:APP:forge-badoptimizations.mixins.json:tick.MixinGameRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23584!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23584!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-Forge.jar:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:notenoughcrashes.forge.mixins.json:client.MixinMain,pl:mixin:APP:smoothboot.mixins.json:client.MainMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:565) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.4.10.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.4.10.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.4.10.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

more info: https://bytebin.lucko.me/XxSmXv0lTE

I really like pquality mod, please fix it. Orz

**Comment by SageofTurtles** [comment]
I'm also encountering this error, crashing my game on startup.  I'm using Forge 47.4.0 for Minecraft 1.20.1, with only Create 6.0.8 and Petrolpark's Library 1.4.21 installed.

Crash report here, if it helps:  https://mclo.gs/8m9G1ZA

**Comment by Polaris-Canis-latrans** [comment]
I reproduce the bug and upload the log.

crash-report: https://mclo.gs/UUM8cXA
lastest.log: https://mclo.gs/PItouqY

I'll add some more testing details: 
1. When selecting "Hold Shift to display quality", the client crashes when the mouse is moved over an item.
2. Choosing to display quality directly causes the client to crash when opening the GUI.

And I have figured out that acquiring items with quality requires the use of tools with specific enchantments for gathering.

**Comment by petrolpark** [comment]
> I'm also encountering this error, crashing my game on startup. I'm using Forge 47.4.0 for Minecraft 1.20.1, with only Create 6.0.8 and Petrolpark's Library 1.4.21 installed.
> 
> Crash report here, if it helps: https://mclo.gs/8m9G1ZA

This is a different bug that was fixed in 1.4.22.

**Comment by Polaris-Canis-latrans** [comment]
I tried installing only the Create 6.0.8、Petrolpark's Library 1.4.23 and pquality 0.2.1 on my server, the client still crash, maybe qpuality also needs an upgrade? And i tried to craft high-quality tools in survival mode, but sticks don't have quality, and the power pump is the same. How should I configure it?

<img width="338" height="139" alt="Image" src="https://github.com/user-attachments/assets/b18091a4-c830-4ee3-b7bf-3b8b04518785" />
<img width="339" height="134" alt="Image" src="https://github.com/user-attachments/assets/08be3515-0272-465a-b74d-9c77b7d22742" />
<img width="34" height="33" alt="Image" src="https://github.com/user-attachments/assets/62411c96-d174-4059-88cf-ac95c84075e4" />
